### PR TITLE
enable bluetooth 

### PR DESCRIPTION
**Pull request by aaayushsingh**
#43 
this enables bluetooth when device searches for adapter. 

tested on the demo app in the readme.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Nice, thank you! 👍 

I don't think iOS will ever allow this btw.

**Comment by EddyVerbruggen** [comment]
I found a better way to programmatically enable Bluetooth on Android: by using an intent the user is prompted automatically and we can fulfil the Promise with the correct (boolean) state when the intent completes. Part of 1.2.0.

**Comment by aaayushsingh** [comment]
Like in [this](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter.html#enable%28%29) link? 
You're going to do this or should I try?

**Comment by EddyVerbruggen** [comment]
It's released!

**Pull request merged**
